version: "3"

services:
  zookeeper:
    image: zookeeper:3.4

  kafka:
    image: wurstmeister/kafka:latest
    hostname: "kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "forwarder_config:1:1, forwarder_status:1:1, forwarder_storage:1:1"

  forwarder:
    image: mbrambilla/forwarder
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: 192.168.99.100
      KAFKA_PORT: 9092
      CONFIG_TOPIC_URI: 192.168.99.100:9092/forwarder_config
      STATUS_TOPIC_URI: 192.168.99.100:9092/forwarder_status
      STORAGE_TOPIC_URI: 192.168.99.100:9092/forwarder_storage
      OUTPUT_BROKER_URI: 192.168.99.100:9092
