version: "3"

services:
  zookeeper:
    image: zookeeper:3.4

  kafka:
    image: wurstmeister/kafka:latest
    hostname: "kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "just-bin-it_config:1:1, just-bin-it_heartbeat:1:1, just-bin-it_response:1:1"

  just-bin-it:
    image: mbrambilla/just-bin-it:latest
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: 192.168.99.100
      BROKER_URI: 192.168.99.100:9092
      CONFIG_TOPIC_URI: just-bin-it_config
      HEARTBEAT_TOPIC_URI: just-bin-it_heartbeat
      RESPONSE_TOPIC_URI: just-bin-it_response
    volumes:
      - ./launch-files/launch_just-bin-it.sh:/launch.sh:ro
      - ./kafkacat:/kafkacat:ro
    command: /launch.sh
