version: "3"

services:
  zookeeper:
    image: zookeeper:3.4

  kafka:
    image: wurstmeister/kafka:latest
    hostname: "kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "detector_events:1:1"

  neutron-event-generator:
    image: mbrambilla:neutron-event-generator
    depends_on:
      - kafka
    volumes:
      - $HOME/work/neventGenerator/amor2020n000889.hdf:/nexusfile.hdf:ro
    environment:
      KAFKA_BROKER: 192.168.99.100:9092
      EVENT_STREAM_TOPIC: "detector_events"
      SOURCE_NEXUS_FILENAME: "/nexusfile.hdf"
      EVENT_STREAM_PATH: "experiment/data"
