version: "3"

services:
  zookeeper:
    image: zookeeper:3.4

  kafka:
    image: wurstmeister/kafka:latest
    hostname: "kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "filewriter_config:1:1, filewriter_status:1:1"

  kafka-to-nexus:
    image: mbrambilla/kafka-to-nexus:latest
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: 192.168.99.100
      KAFKA_PORT: 9092
      COMMAND_TOPIC: filewriter_config
      STATUS_TOPIC: filewriter_status
