#!/bin/bash
export EPICS_BASE=/usr/local/epics/base-3.14.12
export EPICS_HOST_ARCH=RHEL7-x86_64
export PYTHONPATH="/ioc/modules/pyDevSup/koennecke/R3.14.12/lib:/ioc/sinq-ioc/amor-ioc-sim"

/ioc/sinq-ioc/amor-ioc-sim/st.cmd
